export interface InitialUsinaBomRow {
  '[ID_ITEM_ASFALTO]': string;
  '[TRACO]': string;
  '[ID_ITEM_MP]': string;
  '[MP]': string;
  '[CONSUMO]': string;
}

// Fonte: pbi_bom_tracos.json fornecido para a carga inicial.
// Estes dados ficam incorporados ao backend para que a carga seja repetivel
// sem depender do arquivo externo depois da implantacao.
export const INITIAL_USINA_BOM_ROWS: InitialUsinaBomRow[] = [
  {
    '[ID_ITEM_ASFALTO]': '10937',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '31,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '10937',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '16,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '10937',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '10937',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '10937',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '45,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '10938',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '10938',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '10938',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '10938',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '10938',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '12400',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '25,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '12400',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '19',
  },
  {
    '[ID_ITEM_ASFALTO]': '12400',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '12400',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '12400',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '49',
  },
  {
    '[ID_ITEM_ASFALTO]': '12401',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '25,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '12401',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '19',
  },
  {
    '[ID_ITEM_ASFALTO]': '12401',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '12401',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '12401',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '49',
  },
  {
    '[ID_ITEM_ASFALTO]': '12402',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '25,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '12402',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '19',
  },
  {
    '[ID_ITEM_ASFALTO]': '12402',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '12402',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '12402',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '49',
  },
  {
    '[ID_ITEM_ASFALTO]': '1256',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '31,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '1256',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '16,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '1256',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '1256',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '1256',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '45,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13232',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13232',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '11379',
    '[MP]': 'REJEITO ASFALTO RECICLADO',
    '[CONSUMO]': '20',
  },
  {
    '[ID_ITEM_ASFALTO]': '13232',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13232',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13232',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,6',
  },
  {
    '[ID_ITEM_ASFALTO]': '13232',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '27,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13234',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13234',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '11379',
    '[MP]': 'REJEITO ASFALTO RECICLADO',
    '[CONSUMO]': '20',
  },
  {
    '[ID_ITEM_ASFALTO]': '13234',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13234',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13234',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,6',
  },
  {
    '[ID_ITEM_ASFALTO]': '13234',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '27,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13235',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13235',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '11379',
    '[MP]': 'REJEITO ASFALTO RECICLADO',
    '[CONSUMO]': '20',
  },
  {
    '[ID_ITEM_ASFALTO]': '13235',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13235',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13235',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,6',
  },
  {
    '[ID_ITEM_ASFALTO]': '13235',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '27,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13237',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13237',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13237',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13237',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13237',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13345',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '82,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13345',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13345',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '3,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13345',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '13',
  },
  {
    '[ID_ITEM_ASFALTO]': '13346',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '82,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13346',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13346',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '3,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13346',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '13',
  },
  {
    '[ID_ITEM_ASFALTO]': '13347',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '82,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13347',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13347',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '3,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13347',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '13',
  },
  {
    '[ID_ITEM_ASFALTO]': '13348',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '82,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13348',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13348',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '3,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13348',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '13',
  },
  {
    '[ID_ITEM_ASFALTO]': '13349',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '17,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13349',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '59,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13349',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '3,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13349',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13349',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '17,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '13350',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '17,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13350',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '59,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13350',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '3,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13350',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13350',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '17,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '13351',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '17,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13351',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '59,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13351',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '3,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13351',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13351',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '17,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '13352',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '17,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13352',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '59,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13352',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '3,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13352',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13352',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '17,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '13354',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13354',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '13861',
    '[MP]': 'CAP ALTO MODULO',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13354',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13354',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13354',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13355',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13355',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '13861',
    '[MP]': 'CAP ALTO MODULO',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13355',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13355',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13355',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13356',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13356',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '13861',
    '[MP]': 'CAP ALTO MODULO',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13356',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13356',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13356',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13357',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13357',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '13861',
    '[MP]': 'CAP ALTO MODULO',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13357',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13357',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13357',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13872',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '31,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13872',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '16,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '13872',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '13872',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '13872',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '45,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13989',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '33,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13989',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '18',
  },
  {
    '[ID_ITEM_ASFALTO]': '13989',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '13989',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '5525',
    '[MP]': 'CAP BORRACHA (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '13989',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '42,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14217',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '31,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14217',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '16,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14217',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14217',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14217',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '45,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14218',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14218',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '13861',
    '[MP]': 'CAP ALTO MODULO',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14218',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14218',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14218',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14219',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '33,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14219',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '18',
  },
  {
    '[ID_ITEM_ASFALTO]': '14219',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14219',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '5525',
    '[MP]': 'CAP BORRACHA (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14219',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '42,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14220',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '82,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14220',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14220',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '3,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14220',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '13',
  },
  {
    '[ID_ITEM_ASFALTO]': '14221',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '65,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14221',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '14221',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '6,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14221',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '26,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14222',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '17,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14222',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '59,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14222',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '3,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14222',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14222',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '17,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '14223',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14223',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '11379',
    '[MP]': 'REJEITO ASFALTO RECICLADO',
    '[CONSUMO]': '20',
  },
  {
    '[ID_ITEM_ASFALTO]': '14223',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14223',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14223',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,6',
  },
  {
    '[ID_ITEM_ASFALTO]': '14223',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '27,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14224',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14224',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14224',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14224',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14224',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14225',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '25,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14225',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '19',
  },
  {
    '[ID_ITEM_ASFALTO]': '14225',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '14225',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14225',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '49',
  },
  {
    '[ID_ITEM_ASFALTO]': '14247',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '31,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14247',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '16,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14247',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14247',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14247',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '45,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14248',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14248',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '13861',
    '[MP]': 'CAP ALTO MODULO',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14248',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14248',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14248',
    '[TRACO]': 'CCR ALTO MÓDULO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14249',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '33,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14249',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '18',
  },
  {
    '[ID_ITEM_ASFALTO]': '14249',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14249',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '5525',
    '[MP]': 'CAP BORRACHA (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14249',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '42,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14250',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '82,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14250',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14250',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '3,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14250',
    '[TRACO]': 'CPA CCR POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '13',
  },
  {
    '[ID_ITEM_ASFALTO]': '14251',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '65,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14251',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '14251',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '6,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14251',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '26,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14252',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '17,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14252',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '59,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14252',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '3,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14252',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14252',
    '[TRACO]': 'PMQ 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '17,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '14253',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14253',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '11379',
    '[MP]': 'REJEITO ASFALTO RECICLADO',
    '[CONSUMO]': '20',
  },
  {
    '[ID_ITEM_ASFALTO]': '14253',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14253',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14253',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,6',
  },
  {
    '[ID_ITEM_ASFALTO]': '14253',
    '[TRACO]': 'CCR 16/19 RAP',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '27,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14254',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14254',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14254',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14254',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '14254',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14702',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '25,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14702',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '19',
  },
  {
    '[ID_ITEM_ASFALTO]': '14702',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '14702',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '4,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14702',
    '[TRACO]': 'VI POLIMERO',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '49',
  },
  {
    '[ID_ITEM_ASFALTO]': '14703',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '65,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14703',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '14703',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '6,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14703',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '26,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '14704',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '14704',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '23',
  },
  {
    '[ID_ITEM_ASFALTO]': '14704',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14704',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14704',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14706',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14706',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17',
  },
  {
    '[ID_ITEM_ASFALTO]': '14706',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14706',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14706',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41',
  },
  {
    '[ID_ITEM_ASFALTO]': '14707',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14707',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17',
  },
  {
    '[ID_ITEM_ASFALTO]': '14707',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14707',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14707',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41',
  },
  {
    '[ID_ITEM_ASFALTO]': '14708',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14708',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17',
  },
  {
    '[ID_ITEM_ASFALTO]': '14708',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14708',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14708',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41',
  },
  {
    '[ID_ITEM_ASFALTO]': '14710',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14710',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17',
  },
  {
    '[ID_ITEM_ASFALTO]': '14710',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14710',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14710',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41',
  },
  {
    '[ID_ITEM_ASFALTO]': '14711',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14711',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '17',
  },
  {
    '[ID_ITEM_ASFALTO]': '14711',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '14711',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14711',
    '[TRACO]': 'FX C Condominio  50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41',
  },
  {
    '[ID_ITEM_ASFALTO]': '14713',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '14713',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '23',
  },
  {
    '[ID_ITEM_ASFALTO]': '14713',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14713',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14713',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14714',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '14714',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '23',
  },
  {
    '[ID_ITEM_ASFALTO]': '14714',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14714',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14714',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14715',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '14715',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '23',
  },
  {
    '[ID_ITEM_ASFALTO]': '14715',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14715',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14715',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '14716',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '29,3',
  },
  {
    '[ID_ITEM_ASFALTO]': '14716',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '23',
  },
  {
    '[ID_ITEM_ASFALTO]': '14716',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '14716',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '14716',
    '[TRACO]': 'CCR 50/70',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '41,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '2822',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '2822',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '2822',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '2822',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '2822',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '5346',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '33,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '5346',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '18',
  },
  {
    '[ID_ITEM_ASFALTO]': '5346',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '5346',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '5525',
    '[MP]': 'CAP BORRACHA (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '5346',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '42,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '5347',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '33,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '5347',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '18',
  },
  {
    '[ID_ITEM_ASFALTO]': '5347',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '5347',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '5525',
    '[MP]': 'CAP BORRACHA (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '5347',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '42,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '5444',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '31,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '5444',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '16,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '5444',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '5444',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '5444',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '45,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '5642',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '31,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '5642',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '16,5',
  },
  {
    '[ID_ITEM_ASFALTO]': '5642',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '1813',
    '[MP]': 'CAP 50/70 - CIMENTO ASFALTICO DE PETROLEO (USINA)',
    '[CONSUMO]': '4,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '5642',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1',
  },
  {
    '[ID_ITEM_ASFALTO]': '5642',
    '[TRACO]': 'VI  DEINFRA  JR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '45,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '7765',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '33,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '7765',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '18',
  },
  {
    '[ID_ITEM_ASFALTO]': '7765',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '7765',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '5525',
    '[MP]': 'CAP BORRACHA (USINA)',
    '[CONSUMO]': '5,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '7765',
    '[TRACO]': 'VI BORRACHA',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '42,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '7991',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '7991',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '7991',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '7991',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '7991',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '7993',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '35,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '7993',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '1465',
    '[MP]': 'BRITA 3/4',
    '[CONSUMO]': '22,8',
  },
  {
    '[ID_ITEM_ASFALTO]': '7993',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '0,9',
  },
  {
    '[ID_ITEM_ASFALTO]': '7993',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '5',
  },
  {
    '[ID_ITEM_ASFALTO]': '7993',
    '[TRACO]': 'CCR FAIXA 16/19',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '36,1',
  },
  {
    '[ID_ITEM_ASFALTO]': '8395',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '65,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '8395',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '8395',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '6,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '8395',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '26,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '8397',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '111',
    '[MP]': 'PEDRISCO',
    '[CONSUMO]': '65,7',
  },
  {
    '[ID_ITEM_ASFALTO]': '8397',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '2023',
    '[MP]': 'CAL HIDRATADA CH-I',
    '[CONSUMO]': '1,4',
  },
  {
    '[ID_ITEM_ASFALTO]': '8397',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '5643',
    '[MP]': 'CAP POLIMERO POLIFLEX 60/85 - E (USINA)',
    '[CONSUMO]': '6,2',
  },
  {
    '[ID_ITEM_ASFALTO]': '8397',
    '[TRACO]': 'GAP GRADED /CCR',
    '[ID_ITEM_MP]': '968',
    '[MP]': 'PÓ DE PEDRA',
    '[CONSUMO]': '26,7',
  },
];
